package com.reinvent.model;

public class Class {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_classes.cls_id
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private Integer clsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_classes.cls_sht_desc
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String clsShtDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_classes.cls_description
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String clsDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_classes.cls_color
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String clsColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_classes.cls_image
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String clsImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_classes.cls_id
     *
     * @return the value of tt_classes.cls_id
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public Integer getClsId() {
        return clsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_classes.cls_id
     *
     * @param clsId the value for tt_classes.cls_id
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setClsId(Integer clsId) {
        this.clsId = clsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_classes.cls_sht_desc
     *
     * @return the value of tt_classes.cls_sht_desc
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getClsShtDesc() {
        return clsShtDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_classes.cls_sht_desc
     *
     * @param clsShtDesc the value for tt_classes.cls_sht_desc
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setClsShtDesc(String clsShtDesc) {
        this.clsShtDesc = clsShtDesc == null ? null : clsShtDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_classes.cls_description
     *
     * @return the value of tt_classes.cls_description
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getClsDescription() {
        return clsDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_classes.cls_description
     *
     * @param clsDescription the value for tt_classes.cls_description
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setClsDescription(String clsDescription) {
        this.clsDescription = clsDescription == null ? null : clsDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_classes.cls_color
     *
     * @return the value of tt_classes.cls_color
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getClsColor() {
        return clsColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_classes.cls_color
     *
     * @param clsColor the value for tt_classes.cls_color
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setClsColor(String clsColor) {
        this.clsColor = clsColor == null ? null : clsColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_classes.cls_image
     *
     * @return the value of tt_classes.cls_image
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getClsImage() {
        return clsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_classes.cls_image
     *
     * @param clsImage the value for tt_classes.cls_image
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setClsImage(String clsImage) {
        this.clsImage = clsImage == null ? null : clsImage.trim();
    }
}