package com.reinvent.model;

public class Groups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.name
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.id
     *
     * @return the value of groups.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.id
     *
     * @param id the value for groups.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.name
     *
     * @return the value of groups.name
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.name
     *
     * @param name the value for groups.name
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}