package com.reinvent.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.text
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.iconCls
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private String iconcls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parent_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.className
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private String classname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.text
     *
     * @return the value of menu.text
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.text
     *
     * @param text the value for menu.text
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.iconCls
     *
     * @return the value of menu.iconCls
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.iconCls
     *
     * @param iconcls the value for menu.iconCls
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls == null ? null : iconcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parent_id
     *
     * @return the value of menu.parent_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parent_id
     *
     * @param parentId the value for menu.parent_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.className
     *
     * @return the value of menu.className
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.className
     *
     * @param classname the value for menu.className
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }
}