package com.reinvent.model;

public class PermissionsKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.Group_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.Menu_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer menuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.Group_id
     *
     * @return the value of permissions.Group_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.Group_id
     *
     * @param groupId the value for permissions.Group_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.Menu_id
     *
     * @return the value of permissions.Menu_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.Menu_id
     *
     * @param menuId the value for permissions.Menu_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
}