package com.reinvent.model;

public class Subject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_subjects.sub_id
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private Integer subId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_subjects.sub_sht_desc
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String subShtDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_subjects.sub_description
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String subDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_subjects.sub_color
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String subColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_subjects.sub_image
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    private String subImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_subjects.sub_id
     *
     * @return the value of tt_subjects.sub_id
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public Integer getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_subjects.sub_id
     *
     * @param subId the value for tt_subjects.sub_id
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setSubId(Integer subId) {
        this.subId = subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_subjects.sub_sht_desc
     *
     * @return the value of tt_subjects.sub_sht_desc
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getSubShtDesc() {
        return subShtDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_subjects.sub_sht_desc
     *
     * @param subShtDesc the value for tt_subjects.sub_sht_desc
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setSubShtDesc(String subShtDesc) {
        this.subShtDesc = subShtDesc == null ? null : subShtDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_subjects.sub_description
     *
     * @return the value of tt_subjects.sub_description
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getSubDescription() {
        return subDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_subjects.sub_description
     *
     * @param subDescription the value for tt_subjects.sub_description
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setSubDescription(String subDescription) {
        this.subDescription = subDescription == null ? null : subDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_subjects.sub_color
     *
     * @return the value of tt_subjects.sub_color
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getSubColor() {
        return subColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_subjects.sub_color
     *
     * @param subColor the value for tt_subjects.sub_color
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setSubColor(String subColor) {
        this.subColor = subColor == null ? null : subColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_subjects.sub_image
     *
     * @return the value of tt_subjects.sub_image
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getSubImage() {
        return subImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_subjects.sub_image
     *
     * @param subImage the value for tt_subjects.sub_image
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setSubImage(String subImage) {
        this.subImage = subImage == null ? null : subImage.trim();
    }
}