package com.reinvent.model;

import java.util.ArrayList;
import java.util.List;

public class SubjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public SubjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubIdIsNull() {
            addCriterion("sub_id is null");
            return (Criteria) this;
        }

        public Criteria andSubIdIsNotNull() {
            addCriterion("sub_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubIdEqualTo(Integer value) {
            addCriterion("sub_id =", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotEqualTo(Integer value) {
            addCriterion("sub_id <>", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdGreaterThan(Integer value) {
            addCriterion("sub_id >", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub_id >=", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLessThan(Integer value) {
            addCriterion("sub_id <", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLessThanOrEqualTo(Integer value) {
            addCriterion("sub_id <=", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdIn(List<Integer> values) {
            addCriterion("sub_id in", values, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotIn(List<Integer> values) {
            addCriterion("sub_id not in", values, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdBetween(Integer value1, Integer value2) {
            addCriterion("sub_id between", value1, value2, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sub_id not between", value1, value2, "subId");
            return (Criteria) this;
        }

        public Criteria andSubShtDescIsNull() {
            addCriterion("sub_sht_desc is null");
            return (Criteria) this;
        }

        public Criteria andSubShtDescIsNotNull() {
            addCriterion("sub_sht_desc is not null");
            return (Criteria) this;
        }

        public Criteria andSubShtDescEqualTo(String value) {
            addCriterion("sub_sht_desc =", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescNotEqualTo(String value) {
            addCriterion("sub_sht_desc <>", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescGreaterThan(String value) {
            addCriterion("sub_sht_desc >", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescGreaterThanOrEqualTo(String value) {
            addCriterion("sub_sht_desc >=", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescLessThan(String value) {
            addCriterion("sub_sht_desc <", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescLessThanOrEqualTo(String value) {
            addCriterion("sub_sht_desc <=", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescLike(String value) {
            addCriterion("sub_sht_desc like", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescNotLike(String value) {
            addCriterion("sub_sht_desc not like", value, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescIn(List<String> values) {
            addCriterion("sub_sht_desc in", values, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescNotIn(List<String> values) {
            addCriterion("sub_sht_desc not in", values, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescBetween(String value1, String value2) {
            addCriterion("sub_sht_desc between", value1, value2, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubShtDescNotBetween(String value1, String value2) {
            addCriterion("sub_sht_desc not between", value1, value2, "subShtDesc");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionIsNull() {
            addCriterion("sub_description is null");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionIsNotNull() {
            addCriterion("sub_description is not null");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionEqualTo(String value) {
            addCriterion("sub_description =", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionNotEqualTo(String value) {
            addCriterion("sub_description <>", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionGreaterThan(String value) {
            addCriterion("sub_description >", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("sub_description >=", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionLessThan(String value) {
            addCriterion("sub_description <", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionLessThanOrEqualTo(String value) {
            addCriterion("sub_description <=", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionLike(String value) {
            addCriterion("sub_description like", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionNotLike(String value) {
            addCriterion("sub_description not like", value, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionIn(List<String> values) {
            addCriterion("sub_description in", values, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionNotIn(List<String> values) {
            addCriterion("sub_description not in", values, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionBetween(String value1, String value2) {
            addCriterion("sub_description between", value1, value2, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubDescriptionNotBetween(String value1, String value2) {
            addCriterion("sub_description not between", value1, value2, "subDescription");
            return (Criteria) this;
        }

        public Criteria andSubColorIsNull() {
            addCriterion("sub_color is null");
            return (Criteria) this;
        }

        public Criteria andSubColorIsNotNull() {
            addCriterion("sub_color is not null");
            return (Criteria) this;
        }

        public Criteria andSubColorEqualTo(String value) {
            addCriterion("sub_color =", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorNotEqualTo(String value) {
            addCriterion("sub_color <>", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorGreaterThan(String value) {
            addCriterion("sub_color >", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorGreaterThanOrEqualTo(String value) {
            addCriterion("sub_color >=", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorLessThan(String value) {
            addCriterion("sub_color <", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorLessThanOrEqualTo(String value) {
            addCriterion("sub_color <=", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorLike(String value) {
            addCriterion("sub_color like", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorNotLike(String value) {
            addCriterion("sub_color not like", value, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorIn(List<String> values) {
            addCriterion("sub_color in", values, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorNotIn(List<String> values) {
            addCriterion("sub_color not in", values, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorBetween(String value1, String value2) {
            addCriterion("sub_color between", value1, value2, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubColorNotBetween(String value1, String value2) {
            addCriterion("sub_color not between", value1, value2, "subColor");
            return (Criteria) this;
        }

        public Criteria andSubImageIsNull() {
            addCriterion("sub_image is null");
            return (Criteria) this;
        }

        public Criteria andSubImageIsNotNull() {
            addCriterion("sub_image is not null");
            return (Criteria) this;
        }

        public Criteria andSubImageEqualTo(String value) {
            addCriterion("sub_image =", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageNotEqualTo(String value) {
            addCriterion("sub_image <>", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageGreaterThan(String value) {
            addCriterion("sub_image >", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageGreaterThanOrEqualTo(String value) {
            addCriterion("sub_image >=", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageLessThan(String value) {
            addCriterion("sub_image <", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageLessThanOrEqualTo(String value) {
            addCriterion("sub_image <=", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageLike(String value) {
            addCriterion("sub_image like", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageNotLike(String value) {
            addCriterion("sub_image not like", value, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageIn(List<String> values) {
            addCriterion("sub_image in", values, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageNotIn(List<String> values) {
            addCriterion("sub_image not in", values, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageBetween(String value1, String value2) {
            addCriterion("sub_image between", value1, value2, "subImage");
            return (Criteria) this;
        }

        public Criteria andSubImageNotBetween(String value1, String value2) {
            addCriterion("sub_image not between", value1, value2, "subImage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_subjects
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 12 00:25:44 EAT 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tt_subjects
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}