package com.reinvent.model;

public class UserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Group_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Group_id
     *
     * @return the value of user.Group_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Group_id
     *
     * @param groupId the value for user.Group_id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }
}