package com.reinvent.mappers;

import com.reinvent.model.Class;
import com.reinvent.model.ClassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int countByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int deleteByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int deleteByPrimaryKey(Integer clsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int insert(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int insertSelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    List<Class> selectByExample(ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    Class selectByPrimaryKey(Integer clsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int updateByExampleSelective(@Param("record") Class record, @Param("example") ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int updateByExample(@Param("record") Class record, @Param("example") ClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int updateByPrimaryKeySelective(Class record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_classes
     *
     * @mbggenerated Fri Jun 12 00:25:44 EAT 2015
     */
    int updateByPrimaryKey(Class record);
}