package com.reinvent.mappers;

import com.reinvent.model.PermissionsExample;
import com.reinvent.model.PermissionsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int countByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int deleteByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int deleteByPrimaryKey(PermissionsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int insert(PermissionsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int insertSelective(PermissionsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    List<PermissionsKey> selectByExample(PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int updateByExampleSelective(@Param("record") PermissionsKey record, @Param("example") PermissionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permissions
     *
     * @mbggenerated Thu Jun 11 19:52:24 EAT 2015
     */
    int updateByExample(@Param("record") PermissionsKey record, @Param("example") PermissionsExample example);
}